######################################################################
# Automatically generated by qmake (1.07a) Thu Oct 23 14:52:51 2014
######################################################################

TEMPLATE = app
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += stopwatch.h
SOURCES += main.cpp stopwatch.cpp
