######################################################################
# Automatically generated by qmake (2.01a) Mo. Okt 7 15:54:21 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += analogclock.h
SOURCES += analogclock.cpp main.cpp
