#!/bin/sh
# Munin Plugin for DS18S20 Temp Sensor

case $1 in
   config)
        cat <<'EOM'
graph_title Raumtemperatur
graph_vlabel  temperature
temperature.label temperature
EOM
        exit 0;;
esac

echo -n "raumtemp.value "
grep 't=' /sys/bus/w1/devices/w1_bus_master1/10-000802906658/w1_slave | awk -F \
't=' '{print $2/1000}'
